# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thomas/projects/CatacombVita

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thomas/projects/CatacombVita

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/projects/CatacombVita/CMakeFiles /home/thomas/projects/CatacombVita//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/projects/CatacombVita/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Catacomb-Vita

# Build rule for target.
Catacomb-Vita: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catacomb-Vita
.PHONY : Catacomb-Vita

# fast build rule for target.
Catacomb-Vita/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/build
.PHONY : Catacomb-Vita/fast

#=============================================================================
# Target rules for targets named Catacomb-Vita-velf

# Build rule for target.
Catacomb-Vita-velf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catacomb-Vita-velf
.PHONY : Catacomb-Vita-velf

# fast build rule for target.
Catacomb-Vita-velf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita-velf.dir/build.make CMakeFiles/Catacomb-Vita-velf.dir/build
.PHONY : Catacomb-Vita-velf/fast

#=============================================================================
# Target rules for targets named Catacomb-Vita.self-self

# Build rule for target.
Catacomb-Vita.self-self: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catacomb-Vita.self-self
.PHONY : Catacomb-Vita.self-self

# fast build rule for target.
Catacomb-Vita.self-self/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.self-self.dir/build.make CMakeFiles/Catacomb-Vita.self-self.dir/build
.PHONY : Catacomb-Vita.self-self/fast

#=============================================================================
# Target rules for targets named Catacomb-Vita.vpk-vpk

# Build rule for target.
Catacomb-Vita.vpk-vpk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catacomb-Vita.vpk-vpk
.PHONY : Catacomb-Vita.vpk-vpk

# fast build rule for target.
Catacomb-Vita.vpk-vpk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.vpk-vpk.dir/build.make CMakeFiles/Catacomb-Vita.vpk-vpk.dir/build
.PHONY : Catacomb-Vita.vpk-vpk/fast

srcs/cat_play.obj: srcs/cat_play.c.obj
.PHONY : srcs/cat_play.obj

# target to build an object file
srcs/cat_play.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/cat_play.c.obj
.PHONY : srcs/cat_play.c.obj

srcs/cat_play.i: srcs/cat_play.c.i
.PHONY : srcs/cat_play.i

# target to preprocess a source file
srcs/cat_play.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/cat_play.c.i
.PHONY : srcs/cat_play.c.i

srcs/cat_play.s: srcs/cat_play.c.s
.PHONY : srcs/cat_play.s

# target to generate assembly for a file
srcs/cat_play.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/cat_play.c.s
.PHONY : srcs/cat_play.c.s

srcs/catacomb.obj: srcs/catacomb.c.obj
.PHONY : srcs/catacomb.obj

# target to build an object file
srcs/catacomb.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/catacomb.c.obj
.PHONY : srcs/catacomb.c.obj

srcs/catacomb.i: srcs/catacomb.c.i
.PHONY : srcs/catacomb.i

# target to preprocess a source file
srcs/catacomb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/catacomb.c.i
.PHONY : srcs/catacomb.c.i

srcs/catacomb.s: srcs/catacomb.c.s
.PHONY : srcs/catacomb.s

# target to generate assembly for a file
srcs/catacomb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/catacomb.c.s
.PHONY : srcs/catacomb.c.s

srcs/catasm.obj: srcs/catasm.c.obj
.PHONY : srcs/catasm.obj

# target to build an object file
srcs/catasm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/catasm.c.obj
.PHONY : srcs/catasm.c.obj

srcs/catasm.i: srcs/catasm.c.i
.PHONY : srcs/catasm.i

# target to preprocess a source file
srcs/catasm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/catasm.c.i
.PHONY : srcs/catasm.c.i

srcs/catasm.s: srcs/catasm.c.s
.PHONY : srcs/catasm.s

# target to generate assembly for a file
srcs/catasm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/catasm.c.s
.PHONY : srcs/catasm.c.s

srcs/cpanel.obj: srcs/cpanel.c.obj
.PHONY : srcs/cpanel.obj

# target to build an object file
srcs/cpanel.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/cpanel.c.obj
.PHONY : srcs/cpanel.c.obj

srcs/cpanel.i: srcs/cpanel.c.i
.PHONY : srcs/cpanel.i

# target to preprocess a source file
srcs/cpanel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/cpanel.c.i
.PHONY : srcs/cpanel.c.i

srcs/cpanel.s: srcs/cpanel.c.s
.PHONY : srcs/cpanel.s

# target to generate assembly for a file
srcs/cpanel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/cpanel.c.s
.PHONY : srcs/cpanel.c.s

srcs/objects.obj: srcs/objects.c.obj
.PHONY : srcs/objects.obj

# target to build an object file
srcs/objects.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/objects.c.obj
.PHONY : srcs/objects.c.obj

srcs/objects.i: srcs/objects.c.i
.PHONY : srcs/objects.i

# target to preprocess a source file
srcs/objects.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/objects.c.i
.PHONY : srcs/objects.c.i

srcs/objects.s: srcs/objects.c.s
.PHONY : srcs/objects.s

# target to generate assembly for a file
srcs/objects.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/objects.c.s
.PHONY : srcs/objects.c.s

srcs/pcrlib_a.obj: srcs/pcrlib_a.c.obj
.PHONY : srcs/pcrlib_a.obj

# target to build an object file
srcs/pcrlib_a.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/pcrlib_a.c.obj
.PHONY : srcs/pcrlib_a.c.obj

srcs/pcrlib_a.i: srcs/pcrlib_a.c.i
.PHONY : srcs/pcrlib_a.i

# target to preprocess a source file
srcs/pcrlib_a.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/pcrlib_a.c.i
.PHONY : srcs/pcrlib_a.c.i

srcs/pcrlib_a.s: srcs/pcrlib_a.c.s
.PHONY : srcs/pcrlib_a.s

# target to generate assembly for a file
srcs/pcrlib_a.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/pcrlib_a.c.s
.PHONY : srcs/pcrlib_a.c.s

srcs/pcrlib_c.obj: srcs/pcrlib_c.c.obj
.PHONY : srcs/pcrlib_c.obj

# target to build an object file
srcs/pcrlib_c.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/pcrlib_c.c.obj
.PHONY : srcs/pcrlib_c.c.obj

srcs/pcrlib_c.i: srcs/pcrlib_c.c.i
.PHONY : srcs/pcrlib_c.i

# target to preprocess a source file
srcs/pcrlib_c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/pcrlib_c.c.i
.PHONY : srcs/pcrlib_c.c.i

srcs/pcrlib_c.s: srcs/pcrlib_c.c.s
.PHONY : srcs/pcrlib_c.s

# target to generate assembly for a file
srcs/pcrlib_c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/pcrlib_c.c.s
.PHONY : srcs/pcrlib_c.c.s

srcs/rleasm.obj: srcs/rleasm.c.obj
.PHONY : srcs/rleasm.obj

# target to build an object file
srcs/rleasm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/rleasm.c.obj
.PHONY : srcs/rleasm.c.obj

srcs/rleasm.i: srcs/rleasm.c.i
.PHONY : srcs/rleasm.i

# target to preprocess a source file
srcs/rleasm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/rleasm.c.i
.PHONY : srcs/rleasm.c.i

srcs/rleasm.s: srcs/rleasm.c.s
.PHONY : srcs/rleasm.s

# target to generate assembly for a file
srcs/rleasm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Catacomb-Vita.dir/build.make CMakeFiles/Catacomb-Vita.dir/srcs/rleasm.c.s
.PHONY : srcs/rleasm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Catacomb-Vita-velf"
	@echo "... Catacomb-Vita.self-self"
	@echo "... Catacomb-Vita.vpk-vpk"
	@echo "... Catacomb-Vita"
	@echo "... srcs/cat_play.obj"
	@echo "... srcs/cat_play.i"
	@echo "... srcs/cat_play.s"
	@echo "... srcs/catacomb.obj"
	@echo "... srcs/catacomb.i"
	@echo "... srcs/catacomb.s"
	@echo "... srcs/catasm.obj"
	@echo "... srcs/catasm.i"
	@echo "... srcs/catasm.s"
	@echo "... srcs/cpanel.obj"
	@echo "... srcs/cpanel.i"
	@echo "... srcs/cpanel.s"
	@echo "... srcs/objects.obj"
	@echo "... srcs/objects.i"
	@echo "... srcs/objects.s"
	@echo "... srcs/pcrlib_a.obj"
	@echo "... srcs/pcrlib_a.i"
	@echo "... srcs/pcrlib_a.s"
	@echo "... srcs/pcrlib_c.obj"
	@echo "... srcs/pcrlib_c.i"
	@echo "... srcs/pcrlib_c.s"
	@echo "... srcs/rleasm.obj"
	@echo "... srcs/rleasm.i"
	@echo "... srcs/rleasm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

